### ISSUE TITLE
Endless installation of Air SDK

### ISSUE THREAD

**Issue by VladimirVascak** [airsdk/airsdkmanager-releases#14]
How to get rid of items that install endlessly.
One has a meaningless directory D:SHOW_ALL=false\. 

<img width="755" height="458" alt="Image" src="https://github.com/user-attachments/assets/17044c79-8564-451b-bafa-a2f5c2da6fdc" />

**Comment by marchbold** [comment]
Can you update to the latest release, I believe this issue has been resolved.

**Comment by VladimirVascak** [comment]
I uninstalled Air SDK Manager.
I deleted 
C:\Users\\AppData\Roaming\AIRSDKManager
C:\Users\\AppData\Local\AIRSDKManager

I removed 
	AIRSDK_51.1.4\
	AIRSDK_51.2.2\

I installed a new Air SDK Manager.
The problem remains.
I don't know where it stores the paths.

**Comment by ajwfrost** [comment]
Try `c:\users\username\.airsdk\airsdkmanager.db` and maybe the config file there too? There is also a cache folder but unless you see zero-sized files in there, they should be okay to remain I think..

**Comment by VladimirVascak** [comment]
Thank you.
The endless installation is finally over.
There is still a small problem: when starting up, it keeps suggesting a nonsensical path.  

<img width="526" height="387" alt="Image" src="https://github.com/user-attachments/assets/3e99d8a7-3a27-4ded-9990-6fccdd0c2a56" />

**Comment by marchbold** [comment]
If you set it to a new location does it correct?

**Comment by VladimirVascak** [comment]
Thank you,
you were right.
The problem was in the root directory D:\, all I had to do was change the directory.

**Comment by byte127x** [comment]
on linux and i still have an endless installation problem, even after deleting the .airsdk folder

<img width="1709" height="976" alt="Image" src="https://github.com/user-attachments/assets/041f883b-654b-4d80-87f0-414cab271f1c" />

though when watching the downloaded file in the cache, it seems to stop downloading at 31.1MB, which is strange (this happened when downloading 51.3.1 as well)

<img width="616" height="953" alt="Image" src="https://github.com/user-attachments/assets/0251c798-03c2-4c37-8b51-8dd4d6d41dd9" />

**Comment by marchbold** [comment]
@byte127x Seems like a different issue, could you enable debug logging by adding the following line to your `airsdkmanager.cfg` file in the `.airsdk` directory:

```
LOG_LEVEL=debug
```

And then restart the AIR SDK Manager and the download, and send me the `~/.airsdk/logs/airsdkmanager.log` file

**Comment by byte127x** [comment]
deleted the cached .zip.download so that it could try downloading again (though i'm trying version 51.3.1 this time) and enabled the logging like u said

[airsdkmanager.log](https://github.com/user-attachments/files/26196217/airsdkmanager.log)

seems like something is wrong with calculating the downloaded file's checksum? but i'm not knowledgeable enough to know what to fix

**Comment by marchbold** [comment]
Does your system have `shasum` installed normally in `/usr/bin`?

**Comment by byte127x** [comment]
no

but i DO have it somewhere else

<img width="567" height="58" alt="Image" src="https://github.com/user-attachments/assets/21a6ae2c-6e5c-4b81-b58a-c794e4f0327f" />

i also have `sha1sum` and `sha256sum` in my /usr/bin

**Comment by marchbold** [comment]
Ah okay, which linux dist are you using?

**Comment by byte127x** [comment]
arch, but i had the same problem in a fedora vm

**Comment by marchbold** [comment]
I've created a new issue to track this one: https://github.com/airsdk/airsdkmanager-releases/issues/15
